[package]
name = "pyrumqttd"
version = "0.19.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_pyrumqttd"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module", "serde"] }
rumqttd = "0.19.0"